### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined 

### ISSUE THREAD

**Issue by sarsarahman** [seiyria/angular-bootstrap-slider#41]
TypeError: Cannot read property 'prototype' of undefined
    at initSlider (http://127.0.0.1:8000/static/js/angular-bootstrap-slider.js:100:48)
    at link (http://127.0.0.1:8000/static/js/angular-bootstrap-slider.js:24:17)
    at http://127.0.0.1:8000/static/js/angular.js:58:446
    at E (http://127.0.0.1:8000/static/js/angular.js:49:345)
    at f (http://127.0.0.1:8000/static/js/angular.js:42:399)
    at f (http://127.0.0.1:8000/static/js/angular.js:42:416)
    at f (http://127.0.0.1:8000/static/js/angular.js:42:416)
    at f (http://127.0.0.1:8000/static/js/angular.js:42:416)
    at f (http://127.0.0.1:8000/static/js/angular.js:42:416)
    at f (http://127.0.0.1:8000/static/js/angular.js:42:416) <div slider-id="testOptions.sliderId" ng-model="model.first" value="value.first" min="testOptions.min" max="testOptions.max" step="testOptions.step" range="testOptions.range" precision="testOptions.precision" reversed="{{ testOptions.reversed }}" orientation="{{ testOptions.orientation }}" handle="{{ testOptions.handle }}" enabled="{{ testOptions.enabled }}" ng-disabled="{{ testOptions.ngDisabled }}" naturalarrowkeys="{{ testOptions.naturalarrowkeys }}" class="ng-isolate-scope ng-pristine ng-valid">

**Comment by sarsarahman** [comment]
I am using your "bootstrap-slider" as well as your "angular-bootstrap-slider" but getting this error.

**Comment by seiyria** [comment]
I would need a demo, as this by itself isn't really helpful. Unfortunately I don't really work with this often so I couldn't even tell you what the problem is, sorry.

**Comment by sarsarahman** [comment]
http://broker.equityboss.com/ here is the demo 

username : enterprise
password: 123

check into "xprole ideas" section

**Comment by sarsarahman** [comment]
Oh I disabled jquery ui and used 3.x of bootstrap-slider its working fine now... but what should i do to use jquery ui also.?

**Comment by seiyria** [comment]
Please see seiyria/bootstrap-slider#250.

**Comment by figalex** [comment]
I'm having this exact same problem and not using jquery UI. What could it be?
